### ISSUE TITLE
Statistical Analysis of METRIC Results

### ISSUE THREAD

**Issue by NadyaAlexander** [ssj-delta-cu/ssj-ucd-metric#4]
@andybell I wanted to ask you to write some scripts for analyzing the METRIC output rasters.

@qjhart I wonder if we should be writing these with an eye towards the end report / comparison? So the scripting could be re-used for the inter-method comparisons?

Andy - I'm going to start running the CWS code for the 2014-15 water year. I will end up with output rasters of the crop multiplier, Kc, and the daily ETc for the Landsat overpass dates. Eventually we will also have monthly rasters for these. I would like to be able to do a couple different things with the rasters over and over, so I thought your suggestion of an ArcGIS Python script might be best. What I would like to be able to do is:
1. Using the landcover layer, get a mean, standard deviation, 1/2/3 quartile for each crop type for all 4 of the different landcover layers (Level 1, Level 2, spring, young) for ETc (output table).
2. Divide the METRIC ETc rasters by the Spatial CIMIS ETo raster to get a Kc raster, and get the same statistics as (1) above, but for Kc (output raster and table).
3. Subtract the METRIC Kc raster from the Spatial CIMIS based Kc raster so I can see the magnitude / location of the differences (output raster).
4. Be able to look visually at the differences in ETc and Spatial CIMIS based Kc by crop type. Only for Level 2, Spring, and Young crop categories. I'm not sure the best way to set this up, but the idea is that I could pick vineyards, or citrus, or almonds, etc., and pop that category out of a raster (that has a color scale of 0-1.5ish for Kc or 0-10ish for ETc) visually so that I could see where the variability in ETc and Kc for that crop are coming from. So if our method is giving us wonky results for a certain part of the Delta we can see where it's coming from.

How does that sound to you?

**Comment by andybell** [comment]
It looks like the arcgis zonal statistics function doesn't support calculating quartiles. It might be better to use something like [rasterstats](https://github.com/perrygeo/python-rasterstats).

**Comment by andybell** [comment]
Closing this issue. Part 1 is addressed in ssj-overview/et_comparisons.js . Not sure if the other parts are still relevant at this point.
